name: Ruby
on: [push]
jobs:
  test:
    runs-on: ubantu-20.04
    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_DB: github_action_test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_PASSWORD: 
    steps:
      - name: set up Mysql
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DB }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}
